### ISSUE TITLE
Create a GH action to test new installation helper

### ISSUE THREAD

**Issue by njtierney** [greta-dev/greta#415]
- opens a fresh R session, and:

- removes the greta env with conda_remove()
- runs the above code to use a new env
- tries to run a model
- confirms it errors as expected with instructions to create the greta env (check in R with tryCatch)
- creates the greta env as per the instructions

Then:

- opens a fresh R session and:
- tries to run a model
- confirms it works as expected

I think, @goldingn ?

This should be tested in https://github.com/njtierney/greta/tree/only-config-reticulate-357

**Comment by njtierney** [comment]
This could be a composite action: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

See touchstone for a guide: https://github.com/lorenzwalthert/touchstone/tree/main/actions

The idea then is that people can call this installation helper in github actions like they do other ones, e.g., 

```yaml
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        id: install-r
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: greta-dev/actions/setup-greta@v1
```

**Comment by njtierney** [comment]
This now works using `greta_sitrep()` 

![image](https://user-images.githubusercontent.com/6488485/217445107-27f829df-6f0f-4016-8dc5-62980e3ec827.png)

inside of the R CMD Check : https://github.com/greta-dev/greta/blob/4f1cfb58092d7509f3ab6d5298a95e4181ee3c41/.github/workflows/R-CMD-check.yaml#L81-L86

```yaml
      - name: Install greta deps
        run: greta::install_greta_deps(timeout = 50)

      - name: Situation Report on greta install
        run: greta::greta_sitrep()

```

In this PR: https://github.com/greta-dev/greta/pull/534
