### ISSUE TITLE
setup GH actions to run on a cron job

### ISSUE THREAD

**Issue by njtierney** [greta-dev/greta#448]
So that the full tests run every day, or every week (including all the extra distribution tests), so that we can stay on top of changes that might impact us from CRAN (e.g., as noted in #447)

**Comment by njtierney** [comment]
This is pretty straightforward, at the top of the GH actions we a specific `schedule` field.

Here's what we currently have

```yaml
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
```

So we would change this to be

```yaml
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '1 23 * * Sun'
```

`1 23 * * Sun` in CRON times means at 23:01 on Sunday. I figure that every week on a Sunday we can see if there's an issue, then we can see those failures on a Monday.
